// src/components/ChatPage/ChatList/mockChats.js
export const mockChatList = [
    {
        roomId: '1_123456789',
        name: '이지연',
        age: 74,
        gender: 'female',
        lastMessage: '곧 방문 드릴게요!',
        lastMessageTime: '13:30',
        unreadCount: 1,
    },
    {
        roomId: '2_123456789',
        name: '김민수',
        age: 70,
        gender: 'male',
        lastMessage: '잘 다녀오셨어요?',
        lastMessageTime: '13:12',
        unreadCount: 0,
    },
    {
        roomId: '3_123456789',
        name: '박현정',
        age: 78,
        gender: 'female',
        lastMessage: '청소 끝났습니다.',
        lastMessageTime: '12:45',
        unreadCount: 3,
    },
    {
        roomId: '4_123456789',
        name: '오세훈',
        age: 77,
        gender: 'male',
        lastMessage: '약 받아왔습니다.',
        lastMessageTime: '11:10',
        unreadCount: 2,
    },
    {
        roomId: '5_123456789',
        name: '윤정아',
        age: 73,
        gender: 'female',
        lastMessage: '오늘 몇 시에 갈까요?',
        lastMessageTime: '10:55',
        unreadCount: 0,
    },
    {
        roomId: '6_123456789',
        name: '최명호',
        age: 68,
        gender: 'male',
        lastMessage: '산책 잘 마쳤어요.',
        lastMessageTime: '10:03',
        unreadCount: 4,
    },
    {
        roomId: '7_123456789',
        name: '백미자',
        age: 83,
        gender: 'female',
        lastMessage: '다음 주에도 오실 수 있나요?',
        lastMessageTime: '09:27',
        unreadCount: 0,
    },
    {
        roomId: '8_123456789',
        name: '장영자',
        age: 74,
        gender: 'female',
        lastMessage: '감사합니다!',
        lastMessageTime: '08:15',
        unreadCount: 1,
    },
    {
        roomId: '9_123456789',
        name: '정태수',
        age: 81,
        gender: 'male',
        lastMessage: '혈압 측정 완료했습니다.',
        lastMessageTime: '08:01',
        unreadCount: 2,
    },
    {
        roomId: '10_123456789',
        name: '서정희',
        age: 69,
        gender: 'female',
        lastMessage: '책 재미있었어요.',
        lastMessageTime: '07:30',
        unreadCount: 0,
    }
];
